// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbknIMWdyFQ-wmY8BRSBprBj2ejji6xCA',
    appId: '1:153431932343:web:56a70aa4b175153e51fc32',
    messagingSenderId: '153431932343',
    projectId: 'new-app-4df3b',
    authDomain: 'new-app-4df3b.firebaseapp.com',
    storageBucket: 'new-app-4df3b.appspot.com',
    measurementId: 'G-8W46CS6D3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMO79QE2sMw5h_XWB7IRlCT04zwlD5uM',
    appId: '1:153431932343:android:4da1518bc7012fa051fc32',
    messagingSenderId: '153431932343',
    projectId: 'new-app-4df3b',
    storageBucket: 'new-app-4df3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5P6vvQ2r7Vp-sP2bHoM3g6tq6370cXE',
    appId: '1:153431932343:ios:d1ecce06aedf6d4f51fc32',
    messagingSenderId: '153431932343',
    projectId: 'new-app-4df3b',
    storageBucket: 'new-app-4df3b.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa5P6vvQ2r7Vp-sP2bHoM3g6tq6370cXE',
    appId: '1:153431932343:ios:2d4c93ec2a09159451fc32',
    messagingSenderId: '153431932343',
    projectId: 'new-app-4df3b',
    storageBucket: 'new-app-4df3b.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
